from fastapi import FastAPI, UploadFile, File
import torch
from torchvision import transforms
from PIL import Image
import numpy as np
import cv2
from utils import cam_to_color
from model import CNN
from gradcam import GradCAM
from utils import overlay_cam, encode_image
from chatbot import *

app = FastAPI()

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class_names = ["Benign", "Early", "Pre", "Pro"]

model = CNN().to(device)
model.load_state_dict(torch.load("weights/cnn.pth", map_location=device))
model.eval()

gradcam = GradCAM(model, model.conv3)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,)*3,(0.5,)*3)
])

from utils import overlay_cam, encode_image, cam_to_color

@app.post("/api/predict")
async def predict(file: UploadFile = File(...)):
    image = Image.open(file.file).convert("RGB")
    img_np = np.array(image)
    input_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.softmax(outputs, dim=1)
        pred_idx = probs.argmax(dim=1).item()

    cam = gradcam.generate(input_tensor, pred_idx)

    h, w = img_np.shape[:2]
    heatmap_img = cam_to_color(cam, target_size=(w, h))   # standalone heatmap
    overlay_img = overlay_cam(img_np, cam)                # blended overlay

    probabilities = [
        {"label": name, "probability": float(p)}
        for name, p in zip(class_names, probs[0].tolist())
    ]
    probabilities.sort(key=lambda x: x["probability"], reverse=True)

    return {
        "predicted_class": class_names[pred_idx],
        "confidence": float(probs[0][pred_idx]),
        "probabilities": probabilities,
        "original_base64": encode_image(img_np),
        "heatmap_base64": encode_image(heatmap_img),
        "overlay_base64": encode_image(overlay_img),
        "disclaimer": "This result is generated by an AI research prototype and is not a clinical diagnosis."
    }

from typing import Optional
class ChatRequest(BaseModel):
    message: str
    thread_id : Optional[str] = None

class ChatResponse(BaseModel):
    reply: str

@app.post("/api/chat", response_model=ChatResponse)
def chat_endpoint(data: ChatRequest):
    thread_id = data.thread_id or "default_thread"

    result = workflow.invoke({"question": data.message}
                             ,config={
                                 "configurable":{
                                     "thread_id": thread_id
                                 }
                             }
                             )
    return {"reply": result["answer"]}